apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-api
  template:
    metadata:
      labels:
        app: weather-api
    spec:
      env:
      - name: ASPNETCORE_URLS
        value: 'http://0.0.0.0:5000'
      containers:
      - name: weather-api
        image: public.ecr.aws/y8k8e2i0/weather_api:v1
        ports:
        - containerPort: 5000
          protocol: TCP
        imagePullPolicy: Always
        livenessProbe:
            httpGet:
                path: /healthChecks/liveness
                port: 5000
      restartPolicy: Always